# Generated by Django 5.0.6 on 2024-12-12 20:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(help_text='Waga w kilogramach')),
                ('height_m', models.FloatField(help_text='Wzrost w metrach')),
                ('bmi', models.FloatField(blank=True, help_text='BMI (obliczane automatycznie)', null=True)),
                ('fat_percentage', models.FloatField(blank=True, help_text='Procent tkanki tłuszczowej', null=True)),
                ('water_intake_liters', models.FloatField(help_text='Spożycie wody w litrach dziennie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_metric', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('has_training', models.BooleanField(default=False)),
                ('training_type', models.CharField(blank=True, max_length=50, null=True)),
                ('calorie_balance', models.FloatField(default=0.0)),
                ('hydration_level', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa planu treningowego', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Opis planu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Poniedziałek'), ('Tuesday', 'Wtorek'), ('Wednesday', 'Środa'), ('Thursday', 'Czwartek'), ('Friday', 'Piątek'), ('Saturday', 'Sobota'), ('Sunday', 'Niedziela')], max_length=10)),
                ('workout_type', models.CharField(help_text='Typ treningu (np. Cardio, Siłowy)', max_length=50)),
                ('duration_minutes', models.IntegerField(help_text='Czas trwania treningu w minutach')),
                ('description', models.TextField(blank=True, help_text='Szczegóły dotyczące treningu')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='trening.trainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=datetime.date.today, help_text='Data treningu')),
                ('workout_type', models.CharField(help_text='Rodzaj treningu', max_length=50)),
                ('session_duration', models.FloatField(help_text='Czas trwania treningu w godzinach')),
                ('max_bpm', models.IntegerField(blank=True, help_text='Maksymalne tętno podczas sesji', null=True)),
                ('avg_bpm', models.IntegerField(blank=True, help_text='Średnie tętno podczas sesji', null=True)),
                ('resting_bpm', models.IntegerField(blank=True, help_text='Spoczynkowe tętno', null=True)),
                ('calories_burned', models.IntegerField(blank=True, help_text='Ilość spalonych kalorii', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_frequency', models.IntegerField(choices=[(1, '1-2 razy w tygodniu'), (2, '3-4 razy w tygodniu'), (3, '5-7 razy w tygodniu')], help_text='Częstotliwość treningów')),
                ('experience_level', models.IntegerField(choices=[(1, 'Początkujący'), (2, 'Średniozaawansowany'), (3, 'Zaawansowany')], help_text='Poziom doświadczenia')),
                ('goal', models.TextField(blank=True, help_text='Cel treningowy', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
