# Generated by Django 5.0.6 on 2024-12-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymetric',
            name='age',
            field=models.IntegerField(blank=True, help_text='Wiek użytkownika', null=True),
        ),
        migrations.AddField(
            model_name='bodymetric',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Mężczyzna'), ('F', 'Kobieta'), ('O', 'Inna')], help_text='Płeć użytkownika', max_length=1, null=True),
        ),
    ]
