# Generated by Django 5.0.6 on 2024-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0002_bodymetric_age_bodymetric_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymetric',
            name='avg_bpm',
            field=models.IntegerField(blank=True, help_text='Średnie tętno podczas treningu', null=True),
        ),
        migrations.AddField(
            model_name='bodymetric',
            name='max_bpm',
            field=models.IntegerField(blank=True, help_text='Maksymalne tętno podczas treningu', null=True),
        ),
        migrations.AddField(
            model_name='bodymetric',
            name='resting_bpm',
            field=models.IntegerField(blank=True, help_text='Tętno spoczynkowe', null=True),
        ),
    ]
