# Generated by Django 5.0.6 on 2024-12-19 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0003_bodymetric_avg_bpm_bodymetric_max_bpm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingplan',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
