# Generated by Django 5.0.6 on 2024-12-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0004_rename_created_at_trainingplan_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
