# Generated by Django 5.0.6 on 2024-12-20 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0005_trainingsession_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_duration', models.FloatField()),
                ('actual_calories', models.FloatField()),
                ('actual_avg_bpm', models.IntegerField()),
                ('actual_max_bpm', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='trening.trainingsession')),
            ],
        ),
    ]
