# Generated by Django 5.0.6 on 2025-01-06 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0007_exercisehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(blank=True, help_text='Waga w kilogramach', null=True)),
                ('calorie_balance', models.IntegerField(blank=True, help_text='Bilans kaloryczny', null=True)),
                ('hydration', models.FloatField(blank=True, help_text='Nawodnienie w litrach', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
