# Generated by Django 5.0.6 on 2025-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0008_dailyuserstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserstats',
            name='calories_consumed',
            field=models.IntegerField(blank=True, help_text='Kalorie spożyte', null=True),
        ),
    ]
