# Generated by Django 5.0.6 on 2025-01-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0010_notification_reward_traininggoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggoal',
            name='goal_type',
            field=models.CharField(choices=[('weight_loss', 'Zrzucenie wagi'), ('muscle_gain', 'Budowa masy mięśniowej'), ('endurance', 'Wytrzymałość'), ('training_completion', 'Ukończenie treningów')], max_length=255),
        ),
        migrations.AlterField(
            model_name='traininggoal',
            name='target_value',
            field=models.FloatField(help_text='Docelowa wartość (np. waga w kg, liczba godzin treningu, % ukończonych treningów)'),
        ),
    ]
