# Generated by Django 5.0.6 on 2025-01-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trening', '0011_alter_traininggoal_goal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininggoal',
            name='goal_type',
            field=models.CharField(choices=[('weight_loss', 'Zrzucenie wagi'), ('muscle_gain', 'Budowa masy mięśniowej'), ('endurance', 'Wytrzymałość'), ('training_completion', 'Ukończenie treningów'), ('calories_burned', 'Spalenie kalorii')], max_length=255),
        ),
        migrations.AlterField(
            model_name='traininggoal',
            name='target_value',
            field=models.FloatField(help_text='Docelowa wartość (np. waga w kg, liczba godzin treningu, % ukończonych treningów, kalorie)'),
        ),
    ]
